# Generated by Django 3.0.5 on 2020-07-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
